### ISSUE TITLE
system-config-printer-1.5.7 using deprecated API

### ISSUE THREAD

**Issue by fmoro** [funtoo/funtoo-gnome-overlay#2]
Hi,
every time I run emerge command I get a warning saying that system-config-printer-1.5.7.ebuild is using EAPI 5-progress which is deprecated.
Since last stable version is app-admin/system-config-printer-1.5.7-r1 and this ebuild is using EAPI 5, the older one could be just remove instead of upgraded to EAPI 5.

**Comment by danielrobbins** [comment]
This issue has been imported into the Funtoo Linux bug tracker. This helps us to ensure that your bug is prioritized and gets the attention it deserves. You are welcome to create a Funtoo account and participate in the Funtoo Linux workflow or follow-up in the GitHub issue (comments are not currently synchronized.) Follow the action here: https://bugs.funtoo.org/browse/FL-2982

**Comment by danielrobbins** [comment]
This issue has been resolved in the Funtoo Linux bug tracker. Closing on GitHub.
